version: '3'
services:
  app:
    image: cbcr:0.0.1
    ports:
      - 8080:8000
    environment:
      KAFKA_HOST: "192.168.8.124"
      KAFKA_CONSUMER_TOPIC: "card_recognition_source"
      KAFKA_PRODUCER_TOPIC: "card_recognition_target"
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /code
    command: [ 'python', 'cbcr.py' ]
